apiVersion: v1
kind: Service
metadata: # kpt-merge: example/app
  labels:
    app: app
  name: app
  namespace: booking-service
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|example|app'
spec:
  ports:
    - name: "80"
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: app
  type: ClusterIP
