apiVersion: v1
kind: Service
metadata: # kpt-merge: example/app
  labels:
    app: app
  name: app
  namespace: hello-world-kpt
spec:
  ports:
    - name: "80"
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: app
  type: ClusterIP
